#!/bin/bash

# Get system information
HOSTNAME=$(hostname)
OS=$(source /etc/os-release && echo $PRETTY_NAME)
UPTIME=$(uptime -p)

# Get hardware information
CPU=$(lscpu | grep "Model name" | cut -d ':' -f 2 | sed 's/^[ \t]*//')
CPU_SPEED=$(lscpu | grep "CPU MHz" | cut -d ':' -f 2 | sed 's/^[ \t]*//')
RAM=$(free -h | awk '/^Mem/ {print $2}')
DISKS=$(lsblk -o NAME,SIZE,MODEL | tail -n +2 | sed 's/^[ \t]*//')
VIDEO_CARD=$(lspci | grep "VGA" | cut -d ':' -f 3 | sed 's/^[ \t]*//')

# Get network information
FQDN=$(hostname -f)
HOST_ADDRESS=$(hostname -I | awk '{print $1}')
GATEWAY_IP=$(ip route | awk '/default/ {print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | grep "nameserver" | awk '{print $2}')

# Get interface and IP address
INTERFACE_NAME=$(ip a | grep "state UP" | cut -d ':' -f 2 | sed 's/^[ \t]*//')
IP_ADDRESS=$(ip a | grep "inet " | awk '{print $2}')

# Get system status
USERS_LOGGED_IN=$(who | cut -d ' ' -f 1 | sort | uniq | tr '\n' ',')
DISK_SPACE=$(df -h | awk '{print $6, $4}' | tail -n +2)
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(cat /proc/loadavg | awk '{print $1, $2, $3}')
MEMORY_ALLOCATION=$(free -h | awk '/Mem:/ {print $3}')
LISTENING_PORTS=$(ss -tuln | awk '{print $5}' | cut -d ':' -f 2 | sort | uniq | tr '\n' ',')
UFW_RULES=$(sudo ufw status numbered)

# Output the system information report
echo -e "System Report generated by $USER, $(date)\n"

echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS"
echo "Uptime: $UPTIME"

echo -e "\nHardware Information"
echo "--------------------"
echo "CPU: $CPU"
echo "Speed: $CPU_SPEED MHz"
echo "RAM: $RAM"
echo "Disk(s):"
echo "$DISKS"
echo "Video: $VIDEO_CARD"

echo -e "\nNetwork Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $HOST_ADDRESS"
echo "Gateway IP: $GATEWAY_IP"
echo "DNS Server: $DNS_SERVER"
echo "Interface Name: $INTERFACE_NAME"
echo "IP Address: $IP_ADDRESS"

echo -e "\nSystem Status"
echo "-------------"
echo "Users Logged In: $USERS_LOGGED_IN"
echo "Disk Space:"
echo "$DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Memory Allocation: $MEMORY_ALLOCATION"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Rules:"
echo "$UFW_RULES"

# Blank lines for clarity
echo -e "\n"
